### ISSUE TITLE
Help: How to run Fuzzer 

### ISSUE THREAD

**Issue by ghost** [artem-smotrakov/tlsbunny#12]
Tried these steps:

1. `openssl s_server -key server.key -cert server.crt -msg

2. java -version
`OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)`

3. cloned tls bunny

4. cd tlsbunny
5. `mvn clean install -DskipTests`
6. vim tlsbunny.properties
```
server.certificate.path=certs/server_cert.pem
server.key.path=certs/server_key.pkcs8
client.certificate.path=certs/client_cert.pem
client.key.path=certs/client_key.pkcs8
target.host=localhost
target.port=4433
total=10000
```

7. After started tlsbunny command
`java -cp target/tlsbunny-1.0-SNAPSHOT-all.jar \
    com.gypsyengineer.tlsbunny.tls13.client.fuzzer.DeepHandshakeFuzzyClient`

But nothing is happened on server side and client side.

**Comment by artem-smotrakov** [comment]
@skommula96 That is a bug -- thanks for reporting it. The issue should be fixed now. Please pull the latest changes. Please also run the OpenSSL server with `-www` option.

openssl s_server -key certs/server_key.pem -cert certs/server_cert.pem -msg -www

It is necessary because the fuzzer sends an HTTP request and expects a reply.

Please let me know if it still doesn't work.

**Comment by ghost** [comment]
working as expected @artem-smotrakov .
